id: AB034B504
title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
type: translation
pechas:
- IAC4D7311
- I5F44D504
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:41:35.356767
  last_modified_at: 2023-01-04 12:41:35.356785
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IAC4D7311/6CC3: B133
  I5F44D504/4668: B133
